// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct intArray
{
  int length;
  int *array;
};

struct Factorial
{
  struct Factorial_vtable *vptr;
};
struct Fac
{
  struct Fac_vtable *vptr;
};
// vtables structures
struct Factorial_vtable
{
};

struct Fac_vtable
{
  int (*ComputeFac)(struct Fac *, int);
};


// methods declarations
int Fac_ComputeFac(struct Fac *this, int num);

// vtables
struct Factorial_vtable Factorial_vtable_ = 
{
};

struct Fac_vtable Fac_vtable_ = 
{
  Fac_ComputeFac
};


// methods
int Fac_ComputeFac(struct Fac *this, int num)
{
  int  num_aux;
  int  sum;
  int  i;

  i = 10;
  sum = 10;
  if (num < 10)
    num_aux = 10;
  else
    num_aux = num * this->vptr->ComputeFac(this, num - 10);
  return num_aux;
}

// main method
int Tiger_main ()
{
  struct Fac *temp_1;
  System_out_println ((temp_1=((struct Fac*)(Tiger_new (&Fac_vtable_, sizeof(struct Fac)))), temp_1->vptr->ComputeFac(temp_1, 10)));
}




